services:

  imdb_review:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      FASTAPI_ENV: development
    networks:
      - imdb_review

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  selenium:
    image: seleniarm/standalone-firefox
    ports:
      - "4444:4444"
    networks:
      - imdb_review
    logging:
      driver: none
    environment:
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true

networks:
  imdb_review:
    driver: bridge
    