version: '3.9'

services:

  selenium:
    image: seleniarm/standalone-firefox
    ports:
      - 4444:4444
    networks:
      - imdb_review
    logging:
      driver: none

    environment:
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
    
networks:
  imdb_review: